// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	application "weclawbotnotify/services/weclawbotnotify-api/internal/handler/application"
	auth "weclawbotnotify/services/weclawbotnotify-api/internal/handler/auth"
	client "weclawbotnotify/services/weclawbotnotify-api/internal/handler/client"
	health "weclawbotnotify/services/weclawbotnotify-api/internal/handler/health"
	message "weclawbotnotify/services/weclawbotnotify-api/internal/handler/message"
	user "weclawbotnotify/services/weclawbotnotify-api/internal/handler/user"
	"weclawbotnotify/services/weclawbotnotify-api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.ClientAuth},
			[]rest.Route{
				{
					Method:  http.MethodDelete,
					Path:    "/:id",
					Handler: application.DeleteApplicationHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/create",
					Handler: application.CreateApplicationHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: application.ListApplicationsHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/application"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: auth.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: auth.RegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/auth"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.ClientAuth},
			[]rest.Route{
				{
					Method:  http.MethodDelete,
					Path:    "/:id",
					Handler: client.DeleteClientHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/create",
					Handler: client.CreateClientHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: client.ListClientsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/status",
					Handler: client.PollClientStatusHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/client"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/health",
				Handler: health.HealthHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.ClientAuth},
			[]rest.Route{
				{
					Method:  http.MethodDelete,
					Path:    "/:id",
					Handler: message.DeleteMessageHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: message.ListMessagesHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/message"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.ApplicationAuth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/push",
					Handler: message.CreateMessageHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/message"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.ClientAuth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/password",
					Handler: user.ChangePasswordHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/profile",
					Handler: user.GetProfileHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/user"),
	)
}
