// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: ilink.proto

package server

import (
	"context"

	"weclawbotnotify/services/ilink/internal/logic"
	"weclawbotnotify/services/ilink/internal/svc"
	"weclawbotnotify/services/ilink/pb/weclawbotnotify/services/ilink/ilink"
)

type IlinkServer struct {
	svcCtx *svc.ServiceContext
	ilink.UnimplementedIlinkServer
}

func NewIlinkServer(svcCtx *svc.ServiceContext) *IlinkServer {
	return &IlinkServer{
		svcCtx: svcCtx,
	}
}

func (s *IlinkServer) GetQRCode(ctx context.Context, in *ilink.GetQRCodeReq) (*ilink.GetQRCodeResp, error) {
	l := logic.NewGetQRCodeLogic(ctx, s.svcCtx)
	return l.GetQRCode(in)
}

func (s *IlinkServer) PollQRCodeStatus(ctx context.Context, in *ilink.PollQRCodeStatusReq) (*ilink.PollQRCodeStatusResp, error) {
	l := logic.NewPollQRCodeStatusLogic(ctx, s.svcCtx)
	return l.PollQRCodeStatus(in)
}

func (s *IlinkServer) SendMessage(ctx context.Context, in *ilink.SendMessageReq) (*ilink.SendMessageResp, error) {
	l := logic.NewSendMessageLogic(ctx, s.svcCtx)
	return l.SendMessage(in)
}

func (s *IlinkServer) GetUpdates(ctx context.Context, in *ilink.GetUpdatesReq) (*ilink.GetUpdatesResp, error) {
	l := logic.NewGetUpdatesLogic(ctx, s.svcCtx)
	return l.GetUpdates(in)
}
