// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	applicationsFieldNames          = builder.RawFieldNames(&Applications{})
	applicationsRows                = strings.Join(applicationsFieldNames, ",")
	applicationsRowsExpectAutoSet   = strings.Join(stringx.Remove(applicationsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	applicationsRowsWithPlaceHolder = strings.Join(stringx.Remove(applicationsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	applicationsModel interface {
		Insert(ctx context.Context, data *Applications) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Applications, error)
		FindOneByToken(ctx context.Context, token string) (*Applications, error)
		Update(ctx context.Context, data *Applications) error
		Delete(ctx context.Context, id int64) error
	}

	defaultApplicationsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Applications struct {
		Id          int64         `db:"id"`
		UserId      int64         `db:"user_id"`
		Token       string        `db:"token"`
		Name        string        `db:"name"`
		Description string        `db:"description"`
		CreatedAt   int64         `db:"created_at"`
		LastUsedAt  sql.NullInt64 `db:"last_used_at"`
	}
)

func newApplicationsModel(conn sqlx.SqlConn) *defaultApplicationsModel {
	return &defaultApplicationsModel{
		conn:  conn,
		table: "`applications`",
	}
}

func (m *defaultApplicationsModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultApplicationsModel) FindOne(ctx context.Context, id int64) (*Applications, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", applicationsRows, m.table)
	var resp Applications
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultApplicationsModel) FindOneByToken(ctx context.Context, token string) (*Applications, error) {
	var resp Applications
	query := fmt.Sprintf("select %s from %s where `token` = ? limit 1", applicationsRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, token)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultApplicationsModel) Insert(ctx context.Context, data *Applications) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, applicationsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.Token, data.Name, data.Description, data.LastUsedAt)
	return ret, err
}

func (m *defaultApplicationsModel) Update(ctx context.Context, newData *Applications) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, applicationsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.UserId, newData.Token, newData.Name, newData.Description, newData.LastUsedAt, newData.Id)
	return err
}

func (m *defaultApplicationsModel) tableName() string {
	return m.table
}
