// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	clientsFieldNames          = builder.RawFieldNames(&Clients{})
	clientsRows                = strings.Join(clientsFieldNames, ",")
	clientsRowsExpectAutoSet   = strings.Join(stringx.Remove(clientsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	clientsRowsWithPlaceHolder = strings.Join(stringx.Remove(clientsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	clientsModel interface {
		Insert(ctx context.Context, data *Clients) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Clients, error)
		FindOneByToken(ctx context.Context, token string) (*Clients, error)
		Update(ctx context.Context, data *Clients) error
		Delete(ctx context.Context, id int64) error
	}

	defaultClientsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Clients struct {
		Id          int64         `db:"id"`
		UserId      int64         `db:"user_id"`
		Token       string        `db:"token"`
		Name        string        `db:"name"`
		IlinkUserId string        `db:"ilink_user_id"`
		Status      string        `db:"status"`
		CreatedAt   int64         `db:"created_at"`
		LastUsedAt  sql.NullInt64 `db:"last_used_at"`
	}
)

func newClientsModel(conn sqlx.SqlConn) *defaultClientsModel {
	return &defaultClientsModel{
		conn:  conn,
		table: "`clients`",
	}
}

func (m *defaultClientsModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultClientsModel) FindOne(ctx context.Context, id int64) (*Clients, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", clientsRows, m.table)
	var resp Clients
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultClientsModel) FindOneByToken(ctx context.Context, token string) (*Clients, error) {
	var resp Clients
	query := fmt.Sprintf("select %s from %s where `token` = ? limit 1", clientsRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, token)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultClientsModel) Insert(ctx context.Context, data *Clients) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, clientsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.Token, data.Name, data.IlinkUserId, data.Status, data.LastUsedAt)
	return ret, err
}

func (m *defaultClientsModel) Update(ctx context.Context, newData *Clients) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, clientsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.UserId, newData.Token, newData.Name, newData.IlinkUserId, newData.Status, newData.LastUsedAt, newData.Id)
	return err
}

func (m *defaultClientsModel) tableName() string {
	return m.table
}
