// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	refreshTokensFieldNames          = builder.RawFieldNames(&RefreshTokens{})
	refreshTokensRows                = strings.Join(refreshTokensFieldNames, ",")
	refreshTokensRowsExpectAutoSet   = strings.Join(stringx.Remove(refreshTokensFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	refreshTokensRowsWithPlaceHolder = strings.Join(stringx.Remove(refreshTokensFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	refreshTokensModel interface {
		Insert(ctx context.Context, data *RefreshTokens) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*RefreshTokens, error)
		FindOneByJti(ctx context.Context, jti string) (*RefreshTokens, error)
		Update(ctx context.Context, data *RefreshTokens) error
		Delete(ctx context.Context, id int64) error
	}

	defaultRefreshTokensModel struct {
		conn  sqlx.SqlConn
		table string
	}

	RefreshTokens struct {
		Id        int64  `db:"id"`
		UserId    int64  `db:"user_id"`
		Jti       string `db:"jti"`
		Revoked   int64  `db:"revoked"`
		ExpiresAt int64  `db:"expires_at"`
		CreatedAt int64  `db:"created_at"`
	}
)

func newRefreshTokensModel(conn sqlx.SqlConn) *defaultRefreshTokensModel {
	return &defaultRefreshTokensModel{
		conn:  conn,
		table: "`refresh_tokens`",
	}
}

func (m *defaultRefreshTokensModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultRefreshTokensModel) FindOne(ctx context.Context, id int64) (*RefreshTokens, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", refreshTokensRows, m.table)
	var resp RefreshTokens
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultRefreshTokensModel) FindOneByJti(ctx context.Context, jti string) (*RefreshTokens, error) {
	var resp RefreshTokens
	query := fmt.Sprintf("select %s from %s where `jti` = ? limit 1", refreshTokensRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, jti)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultRefreshTokensModel) Insert(ctx context.Context, data *RefreshTokens) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, refreshTokensRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.Jti, data.Revoked, data.ExpiresAt)
	return ret, err
}

func (m *defaultRefreshTokensModel) Update(ctx context.Context, newData *RefreshTokens) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, refreshTokensRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.UserId, newData.Jti, newData.Revoked, newData.ExpiresAt, newData.Id)
	return err
}

func (m *defaultRefreshTokensModel) tableName() string {
	return m.table
}
