// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v7.34.1
// source: ilink.proto

package ilink

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetQRCodeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BotType       int32                  `protobuf:"varint,1,opt,name=bot_type,json=botType,proto3" json:"bot_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQRCodeReq) Reset() {
	*x = GetQRCodeReq{}
	mi := &file_ilink_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQRCodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQRCodeReq) ProtoMessage() {}

func (x *GetQRCodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_ilink_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQRCodeReq.ProtoReflect.Descriptor instead.
func (*GetQRCodeReq) Descriptor() ([]byte, []int) {
	return file_ilink_proto_rawDescGZIP(), []int{0}
}

func (x *GetQRCodeReq) GetBotType() int32 {
	if x != nil {
		return x.BotType
	}
	return 0
}

type GetQRCodeResp struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Qrcode           string                 `protobuf:"bytes,1,opt,name=qrcode,proto3" json:"qrcode,omitempty"`
	QrcodeImgContent string                 `protobuf:"bytes,2,opt,name=qrcode_img_content,json=qrcodeImgContent,proto3" json:"qrcode_img_content,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetQRCodeResp) Reset() {
	*x = GetQRCodeResp{}
	mi := &file_ilink_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQRCodeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQRCodeResp) ProtoMessage() {}

func (x *GetQRCodeResp) ProtoReflect() protoreflect.Message {
	mi := &file_ilink_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQRCodeResp.ProtoReflect.Descriptor instead.
func (*GetQRCodeResp) Descriptor() ([]byte, []int) {
	return file_ilink_proto_rawDescGZIP(), []int{1}
}

func (x *GetQRCodeResp) GetQrcode() string {
	if x != nil {
		return x.Qrcode
	}
	return ""
}

func (x *GetQRCodeResp) GetQrcodeImgContent() string {
	if x != nil {
		return x.QrcodeImgContent
	}
	return ""
}

type PollQRCodeStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Qrcode        string                 `protobuf:"bytes,1,opt,name=qrcode,proto3" json:"qrcode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollQRCodeStatusReq) Reset() {
	*x = PollQRCodeStatusReq{}
	mi := &file_ilink_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollQRCodeStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollQRCodeStatusReq) ProtoMessage() {}

func (x *PollQRCodeStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_ilink_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollQRCodeStatusReq.ProtoReflect.Descriptor instead.
func (*PollQRCodeStatusReq) Descriptor() ([]byte, []int) {
	return file_ilink_proto_rawDescGZIP(), []int{2}
}

func (x *PollQRCodeStatusReq) GetQrcode() string {
	if x != nil {
		return x.Qrcode
	}
	return ""
}

type PollQRCodeStatusResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	BotToken      string                 `protobuf:"bytes,2,opt,name=bot_token,json=botToken,proto3" json:"bot_token,omitempty"`
	IlinkBotId    string                 `protobuf:"bytes,3,opt,name=ilink_bot_id,json=ilinkBotId,proto3" json:"ilink_bot_id,omitempty"`
	BaseUrl       string                 `protobuf:"bytes,4,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	IlinkUserId   string                 `protobuf:"bytes,5,opt,name=ilink_user_id,json=ilinkUserId,proto3" json:"ilink_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollQRCodeStatusResp) Reset() {
	*x = PollQRCodeStatusResp{}
	mi := &file_ilink_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollQRCodeStatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollQRCodeStatusResp) ProtoMessage() {}

func (x *PollQRCodeStatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_ilink_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollQRCodeStatusResp.ProtoReflect.Descriptor instead.
func (*PollQRCodeStatusResp) Descriptor() ([]byte, []int) {
	return file_ilink_proto_rawDescGZIP(), []int{3}
}

func (x *PollQRCodeStatusResp) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PollQRCodeStatusResp) GetBotToken() string {
	if x != nil {
		return x.BotToken
	}
	return ""
}

func (x *PollQRCodeStatusResp) GetIlinkBotId() string {
	if x != nil {
		return x.IlinkBotId
	}
	return ""
}

func (x *PollQRCodeStatusResp) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *PollQRCodeStatusResp) GetIlinkUserId() string {
	if x != nil {
		return x.IlinkUserId
	}
	return ""
}

type SendMessageReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BotToken      string                 `protobuf:"bytes,1,opt,name=bot_token,json=botToken,proto3" json:"bot_token,omitempty"`
	BaseUrl       string                 `protobuf:"bytes,2,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	ToUserId      string                 `protobuf:"bytes,3,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	ContextToken  string                 `protobuf:"bytes,5,opt,name=context_token,json=contextToken,proto3" json:"context_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageReq) Reset() {
	*x = SendMessageReq{}
	mi := &file_ilink_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageReq) ProtoMessage() {}

func (x *SendMessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_ilink_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageReq.ProtoReflect.Descriptor instead.
func (*SendMessageReq) Descriptor() ([]byte, []int) {
	return file_ilink_proto_rawDescGZIP(), []int{4}
}

func (x *SendMessageReq) GetBotToken() string {
	if x != nil {
		return x.BotToken
	}
	return ""
}

func (x *SendMessageReq) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *SendMessageReq) GetToUserId() string {
	if x != nil {
		return x.ToUserId
	}
	return ""
}

func (x *SendMessageReq) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SendMessageReq) GetContextToken() string {
	if x != nil {
		return x.ContextToken
	}
	return ""
}

type SendMessageResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ret           int32                  `protobuf:"varint,1,opt,name=ret,proto3" json:"ret,omitempty"`
	ErrMsg        string                 `protobuf:"bytes,2,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResp) Reset() {
	*x = SendMessageResp{}
	mi := &file_ilink_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResp) ProtoMessage() {}

func (x *SendMessageResp) ProtoReflect() protoreflect.Message {
	mi := &file_ilink_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResp.ProtoReflect.Descriptor instead.
func (*SendMessageResp) Descriptor() ([]byte, []int) {
	return file_ilink_proto_rawDescGZIP(), []int{5}
}

func (x *SendMessageResp) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *SendMessageResp) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

type GetUpdatesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BotToken      string                 `protobuf:"bytes,1,opt,name=bot_token,json=botToken,proto3" json:"bot_token,omitempty"`
	BaseUrl       string                 `protobuf:"bytes,2,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	GetUpdatesBuf string                 `protobuf:"bytes,3,opt,name=get_updates_buf,json=getUpdatesBuf,proto3" json:"get_updates_buf,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUpdatesReq) Reset() {
	*x = GetUpdatesReq{}
	mi := &file_ilink_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUpdatesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUpdatesReq) ProtoMessage() {}

func (x *GetUpdatesReq) ProtoReflect() protoreflect.Message {
	mi := &file_ilink_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUpdatesReq.ProtoReflect.Descriptor instead.
func (*GetUpdatesReq) Descriptor() ([]byte, []int) {
	return file_ilink_proto_rawDescGZIP(), []int{6}
}

func (x *GetUpdatesReq) GetBotToken() string {
	if x != nil {
		return x.BotToken
	}
	return ""
}

func (x *GetUpdatesReq) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *GetUpdatesReq) GetGetUpdatesBuf() string {
	if x != nil {
		return x.GetUpdatesBuf
	}
	return ""
}

type GetUpdatesResp struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Ret                  int32                  `protobuf:"varint,1,opt,name=ret,proto3" json:"ret,omitempty"`
	ErrCode              int32                  `protobuf:"varint,2,opt,name=err_code,json=errCode,proto3" json:"err_code,omitempty"`
	ErrMsg               string                 `protobuf:"bytes,3,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
	GetUpdatesBuf        string                 `protobuf:"bytes,4,opt,name=get_updates_buf,json=getUpdatesBuf,proto3" json:"get_updates_buf,omitempty"`
	LongPollingTimeoutMs int32                  `protobuf:"varint,5,opt,name=long_polling_timeout_ms,json=longPollingTimeoutMs,proto3" json:"long_polling_timeout_ms,omitempty"`
	Msgs                 []*WeixinMessage       `protobuf:"bytes,6,rep,name=msgs,proto3" json:"msgs,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetUpdatesResp) Reset() {
	*x = GetUpdatesResp{}
	mi := &file_ilink_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUpdatesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUpdatesResp) ProtoMessage() {}

func (x *GetUpdatesResp) ProtoReflect() protoreflect.Message {
	mi := &file_ilink_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUpdatesResp.ProtoReflect.Descriptor instead.
func (*GetUpdatesResp) Descriptor() ([]byte, []int) {
	return file_ilink_proto_rawDescGZIP(), []int{7}
}

func (x *GetUpdatesResp) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *GetUpdatesResp) GetErrCode() int32 {
	if x != nil {
		return x.ErrCode
	}
	return 0
}

func (x *GetUpdatesResp) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

func (x *GetUpdatesResp) GetGetUpdatesBuf() string {
	if x != nil {
		return x.GetUpdatesBuf
	}
	return ""
}

func (x *GetUpdatesResp) GetLongPollingTimeoutMs() int32 {
	if x != nil {
		return x.LongPollingTimeoutMs
	}
	return 0
}

func (x *GetUpdatesResp) GetMsgs() []*WeixinMessage {
	if x != nil {
		return x.Msgs
	}
	return nil
}

type WeixinMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           int32                  `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	MessageId     int64                  `protobuf:"varint,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	FromUserId    string                 `protobuf:"bytes,3,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`
	ToUserId      string                 `protobuf:"bytes,4,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`
	MessageType   int32                  `protobuf:"varint,5,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	MessageState  int32                  `protobuf:"varint,6,opt,name=message_state,json=messageState,proto3" json:"message_state,omitempty"`
	ItemList      []*MessageItem         `protobuf:"bytes,7,rep,name=item_list,json=itemList,proto3" json:"item_list,omitempty"`
	ContextToken  string                 `protobuf:"bytes,8,opt,name=context_token,json=contextToken,proto3" json:"context_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WeixinMessage) Reset() {
	*x = WeixinMessage{}
	mi := &file_ilink_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeixinMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeixinMessage) ProtoMessage() {}

func (x *WeixinMessage) ProtoReflect() protoreflect.Message {
	mi := &file_ilink_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeixinMessage.ProtoReflect.Descriptor instead.
func (*WeixinMessage) Descriptor() ([]byte, []int) {
	return file_ilink_proto_rawDescGZIP(), []int{8}
}

func (x *WeixinMessage) GetSeq() int32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *WeixinMessage) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *WeixinMessage) GetFromUserId() string {
	if x != nil {
		return x.FromUserId
	}
	return ""
}

func (x *WeixinMessage) GetToUserId() string {
	if x != nil {
		return x.ToUserId
	}
	return ""
}

func (x *WeixinMessage) GetMessageType() int32 {
	if x != nil {
		return x.MessageType
	}
	return 0
}

func (x *WeixinMessage) GetMessageState() int32 {
	if x != nil {
		return x.MessageState
	}
	return 0
}

func (x *WeixinMessage) GetItemList() []*MessageItem {
	if x != nil {
		return x.ItemList
	}
	return nil
}

func (x *WeixinMessage) GetContextToken() string {
	if x != nil {
		return x.ContextToken
	}
	return ""
}

type MessageItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          int32                  `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	TextItem      *TextItem              `protobuf:"bytes,2,opt,name=text_item,json=textItem,proto3" json:"text_item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageItem) Reset() {
	*x = MessageItem{}
	mi := &file_ilink_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageItem) ProtoMessage() {}

func (x *MessageItem) ProtoReflect() protoreflect.Message {
	mi := &file_ilink_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageItem.ProtoReflect.Descriptor instead.
func (*MessageItem) Descriptor() ([]byte, []int) {
	return file_ilink_proto_rawDescGZIP(), []int{9}
}

func (x *MessageItem) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *MessageItem) GetTextItem() *TextItem {
	if x != nil {
		return x.TextItem
	}
	return nil
}

type TextItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextItem) Reset() {
	*x = TextItem{}
	mi := &file_ilink_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextItem) ProtoMessage() {}

func (x *TextItem) ProtoReflect() protoreflect.Message {
	mi := &file_ilink_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextItem.ProtoReflect.Descriptor instead.
func (*TextItem) Descriptor() ([]byte, []int) {
	return file_ilink_proto_rawDescGZIP(), []int{10}
}

func (x *TextItem) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_ilink_proto protoreflect.FileDescriptor

const file_ilink_proto_rawDesc = "" +
	"\n" +
	"\vilink.proto\x12\x05ilink\")\n" +
	"\fGetQRCodeReq\x12\x19\n" +
	"\bbot_type\x18\x01 \x01(\x05R\abotType\"U\n" +
	"\rGetQRCodeResp\x12\x16\n" +
	"\x06qrcode\x18\x01 \x01(\tR\x06qrcode\x12,\n" +
	"\x12qrcode_img_content\x18\x02 \x01(\tR\x10qrcodeImgContent\"-\n" +
	"\x13PollQRCodeStatusReq\x12\x16\n" +
	"\x06qrcode\x18\x01 \x01(\tR\x06qrcode\"\xac\x01\n" +
	"\x14PollQRCodeStatusResp\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1b\n" +
	"\tbot_token\x18\x02 \x01(\tR\bbotToken\x12 \n" +
	"\filink_bot_id\x18\x03 \x01(\tR\n" +
	"ilinkBotId\x12\x19\n" +
	"\bbase_url\x18\x04 \x01(\tR\abaseUrl\x12\"\n" +
	"\rilink_user_id\x18\x05 \x01(\tR\vilinkUserId\"\x9f\x01\n" +
	"\x0eSendMessageReq\x12\x1b\n" +
	"\tbot_token\x18\x01 \x01(\tR\bbotToken\x12\x19\n" +
	"\bbase_url\x18\x02 \x01(\tR\abaseUrl\x12\x1c\n" +
	"\n" +
	"to_user_id\x18\x03 \x01(\tR\btoUserId\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x12#\n" +
	"\rcontext_token\x18\x05 \x01(\tR\fcontextToken\"<\n" +
	"\x0fSendMessageResp\x12\x10\n" +
	"\x03ret\x18\x01 \x01(\x05R\x03ret\x12\x17\n" +
	"\aerr_msg\x18\x02 \x01(\tR\x06errMsg\"o\n" +
	"\rGetUpdatesReq\x12\x1b\n" +
	"\tbot_token\x18\x01 \x01(\tR\bbotToken\x12\x19\n" +
	"\bbase_url\x18\x02 \x01(\tR\abaseUrl\x12&\n" +
	"\x0fget_updates_buf\x18\x03 \x01(\tR\rgetUpdatesBuf\"\xdf\x01\n" +
	"\x0eGetUpdatesResp\x12\x10\n" +
	"\x03ret\x18\x01 \x01(\x05R\x03ret\x12\x19\n" +
	"\berr_code\x18\x02 \x01(\x05R\aerrCode\x12\x17\n" +
	"\aerr_msg\x18\x03 \x01(\tR\x06errMsg\x12&\n" +
	"\x0fget_updates_buf\x18\x04 \x01(\tR\rgetUpdatesBuf\x125\n" +
	"\x17long_polling_timeout_ms\x18\x05 \x01(\x05R\x14longPollingTimeoutMs\x12(\n" +
	"\x04msgs\x18\x06 \x03(\v2\x14.ilink.WeixinMessageR\x04msgs\"\x9e\x02\n" +
	"\rWeixinMessage\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x05R\x03seq\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\x03R\tmessageId\x12 \n" +
	"\ffrom_user_id\x18\x03 \x01(\tR\n" +
	"fromUserId\x12\x1c\n" +
	"\n" +
	"to_user_id\x18\x04 \x01(\tR\btoUserId\x12!\n" +
	"\fmessage_type\x18\x05 \x01(\x05R\vmessageType\x12#\n" +
	"\rmessage_state\x18\x06 \x01(\x05R\fmessageState\x12/\n" +
	"\titem_list\x18\a \x03(\v2\x12.ilink.MessageItemR\bitemList\x12#\n" +
	"\rcontext_token\x18\b \x01(\tR\fcontextToken\"O\n" +
	"\vMessageItem\x12\x12\n" +
	"\x04type\x18\x01 \x01(\x05R\x04type\x12,\n" +
	"\ttext_item\x18\x02 \x01(\v2\x0f.ilink.TextItemR\btextItem\"\x1e\n" +
	"\bTextItem\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text2\x85\x02\n" +
	"\x05Ilink\x126\n" +
	"\tGetQRCode\x12\x13.ilink.GetQRCodeReq\x1a\x14.ilink.GetQRCodeResp\x12K\n" +
	"\x10PollQRCodeStatus\x12\x1a.ilink.PollQRCodeStatusReq\x1a\x1b.ilink.PollQRCodeStatusResp\x12<\n" +
	"\vSendMessage\x12\x15.ilink.SendMessageReq\x1a\x16.ilink.SendMessageResp\x129\n" +
	"\n" +
	"GetUpdates\x12\x14.ilink.GetUpdatesReq\x1a\x15.ilink.GetUpdatesRespB&Z$weclawbotnotify/services/ilink/ilinkb\x06proto3"

var (
	file_ilink_proto_rawDescOnce sync.Once
	file_ilink_proto_rawDescData []byte
)

func file_ilink_proto_rawDescGZIP() []byte {
	file_ilink_proto_rawDescOnce.Do(func() {
		file_ilink_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ilink_proto_rawDesc), len(file_ilink_proto_rawDesc)))
	})
	return file_ilink_proto_rawDescData
}

var file_ilink_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_ilink_proto_goTypes = []any{
	(*GetQRCodeReq)(nil),         // 0: ilink.GetQRCodeReq
	(*GetQRCodeResp)(nil),        // 1: ilink.GetQRCodeResp
	(*PollQRCodeStatusReq)(nil),  // 2: ilink.PollQRCodeStatusReq
	(*PollQRCodeStatusResp)(nil), // 3: ilink.PollQRCodeStatusResp
	(*SendMessageReq)(nil),       // 4: ilink.SendMessageReq
	(*SendMessageResp)(nil),      // 5: ilink.SendMessageResp
	(*GetUpdatesReq)(nil),        // 6: ilink.GetUpdatesReq
	(*GetUpdatesResp)(nil),       // 7: ilink.GetUpdatesResp
	(*WeixinMessage)(nil),        // 8: ilink.WeixinMessage
	(*MessageItem)(nil),          // 9: ilink.MessageItem
	(*TextItem)(nil),             // 10: ilink.TextItem
}
var file_ilink_proto_depIdxs = []int32{
	8,  // 0: ilink.GetUpdatesResp.msgs:type_name -> ilink.WeixinMessage
	9,  // 1: ilink.WeixinMessage.item_list:type_name -> ilink.MessageItem
	10, // 2: ilink.MessageItem.text_item:type_name -> ilink.TextItem
	0,  // 3: ilink.Ilink.GetQRCode:input_type -> ilink.GetQRCodeReq
	2,  // 4: ilink.Ilink.PollQRCodeStatus:input_type -> ilink.PollQRCodeStatusReq
	4,  // 5: ilink.Ilink.SendMessage:input_type -> ilink.SendMessageReq
	6,  // 6: ilink.Ilink.GetUpdates:input_type -> ilink.GetUpdatesReq
	1,  // 7: ilink.Ilink.GetQRCode:output_type -> ilink.GetQRCodeResp
	3,  // 8: ilink.Ilink.PollQRCodeStatus:output_type -> ilink.PollQRCodeStatusResp
	5,  // 9: ilink.Ilink.SendMessage:output_type -> ilink.SendMessageResp
	7,  // 10: ilink.Ilink.GetUpdates:output_type -> ilink.GetUpdatesResp
	7,  // [7:11] is the sub-list for method output_type
	3,  // [3:7] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_ilink_proto_init() }
func file_ilink_proto_init() {
	if File_ilink_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ilink_proto_rawDesc), len(file_ilink_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ilink_proto_goTypes,
		DependencyIndexes: file_ilink_proto_depIdxs,
		MessageInfos:      file_ilink_proto_msgTypes,
	}.Build()
	File_ilink_proto = out.File
	file_ilink_proto_goTypes = nil
	file_ilink_proto_depIdxs = nil
}
