// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.1
// source: ilink.proto

package ilink

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Ilink_GetQRCode_FullMethodName        = "/ilink.Ilink/GetQRCode"
	Ilink_PollQRCodeStatus_FullMethodName = "/ilink.Ilink/PollQRCodeStatus"
	Ilink_SendMessage_FullMethodName      = "/ilink.Ilink/SendMessage"
	Ilink_GetUpdates_FullMethodName       = "/ilink.Ilink/GetUpdates"
)

// IlinkClient is the client API for Ilink service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IlinkClient interface {
	GetQRCode(ctx context.Context, in *GetQRCodeReq, opts ...grpc.CallOption) (*GetQRCodeResp, error)
	PollQRCodeStatus(ctx context.Context, in *PollQRCodeStatusReq, opts ...grpc.CallOption) (*PollQRCodeStatusResp, error)
	SendMessage(ctx context.Context, in *SendMessageReq, opts ...grpc.CallOption) (*SendMessageResp, error)
	GetUpdates(ctx context.Context, in *GetUpdatesReq, opts ...grpc.CallOption) (*GetUpdatesResp, error)
}

type ilinkClient struct {
	cc grpc.ClientConnInterface
}

func NewIlinkClient(cc grpc.ClientConnInterface) IlinkClient {
	return &ilinkClient{cc}
}

func (c *ilinkClient) GetQRCode(ctx context.Context, in *GetQRCodeReq, opts ...grpc.CallOption) (*GetQRCodeResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetQRCodeResp)
	err := c.cc.Invoke(ctx, Ilink_GetQRCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ilinkClient) PollQRCodeStatus(ctx context.Context, in *PollQRCodeStatusReq, opts ...grpc.CallOption) (*PollQRCodeStatusResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PollQRCodeStatusResp)
	err := c.cc.Invoke(ctx, Ilink_PollQRCodeStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ilinkClient) SendMessage(ctx context.Context, in *SendMessageReq, opts ...grpc.CallOption) (*SendMessageResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendMessageResp)
	err := c.cc.Invoke(ctx, Ilink_SendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ilinkClient) GetUpdates(ctx context.Context, in *GetUpdatesReq, opts ...grpc.CallOption) (*GetUpdatesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUpdatesResp)
	err := c.cc.Invoke(ctx, Ilink_GetUpdates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IlinkServer is the server API for Ilink service.
// All implementations must embed UnimplementedIlinkServer
// for forward compatibility.
type IlinkServer interface {
	GetQRCode(context.Context, *GetQRCodeReq) (*GetQRCodeResp, error)
	PollQRCodeStatus(context.Context, *PollQRCodeStatusReq) (*PollQRCodeStatusResp, error)
	SendMessage(context.Context, *SendMessageReq) (*SendMessageResp, error)
	GetUpdates(context.Context, *GetUpdatesReq) (*GetUpdatesResp, error)
	mustEmbedUnimplementedIlinkServer()
}

// UnimplementedIlinkServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIlinkServer struct{}

func (UnimplementedIlinkServer) GetQRCode(context.Context, *GetQRCodeReq) (*GetQRCodeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetQRCode not implemented")
}
func (UnimplementedIlinkServer) PollQRCodeStatus(context.Context, *PollQRCodeStatusReq) (*PollQRCodeStatusResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PollQRCodeStatus not implemented")
}
func (UnimplementedIlinkServer) SendMessage(context.Context, *SendMessageReq) (*SendMessageResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedIlinkServer) GetUpdates(context.Context, *GetUpdatesReq) (*GetUpdatesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUpdates not implemented")
}
func (UnimplementedIlinkServer) mustEmbedUnimplementedIlinkServer() {}
func (UnimplementedIlinkServer) testEmbeddedByValue()               {}

// UnsafeIlinkServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IlinkServer will
// result in compilation errors.
type UnsafeIlinkServer interface {
	mustEmbedUnimplementedIlinkServer()
}

func RegisterIlinkServer(s grpc.ServiceRegistrar, srv IlinkServer) {
	// If the following call pancis, it indicates UnimplementedIlinkServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Ilink_ServiceDesc, srv)
}

func _Ilink_GetQRCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetQRCodeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IlinkServer).GetQRCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ilink_GetQRCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IlinkServer).GetQRCode(ctx, req.(*GetQRCodeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ilink_PollQRCodeStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PollQRCodeStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IlinkServer).PollQRCodeStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ilink_PollQRCodeStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IlinkServer).PollQRCodeStatus(ctx, req.(*PollQRCodeStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ilink_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IlinkServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ilink_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IlinkServer).SendMessage(ctx, req.(*SendMessageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ilink_GetUpdates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUpdatesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IlinkServer).GetUpdates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ilink_GetUpdates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IlinkServer).GetUpdates(ctx, req.(*GetUpdatesReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Ilink_ServiceDesc is the grpc.ServiceDesc for Ilink service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Ilink_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ilink.Ilink",
	HandlerType: (*IlinkServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetQRCode",
			Handler:    _Ilink_GetQRCode_Handler,
		},
		{
			MethodName: "PollQRCodeStatus",
			Handler:    _Ilink_PollQRCodeStatus_Handler,
		},
		{
			MethodName: "SendMessage",
			Handler:    _Ilink_SendMessage_Handler,
		},
		{
			MethodName: "GetUpdates",
			Handler:    _Ilink_GetUpdates_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ilink.proto",
}
