// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: ilink.proto

package ilinkclient

import (
	"context"

	"weclawbotnotify/services/ilink/pb/weclawbotnotify/services/ilink/ilink"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetQRCodeReq         = ilink.GetQRCodeReq
	GetQRCodeResp        = ilink.GetQRCodeResp
	GetUpdatesReq        = ilink.GetUpdatesReq
	GetUpdatesResp       = ilink.GetUpdatesResp
	MessageItem          = ilink.MessageItem
	PollQRCodeStatusReq  = ilink.PollQRCodeStatusReq
	PollQRCodeStatusResp = ilink.PollQRCodeStatusResp
	SendMessageReq       = ilink.SendMessageReq
	SendMessageResp      = ilink.SendMessageResp
	TextItem             = ilink.TextItem
	WeixinMessage        = ilink.WeixinMessage

	Ilink interface {
		GetQRCode(ctx context.Context, in *GetQRCodeReq, opts ...grpc.CallOption) (*GetQRCodeResp, error)
		PollQRCodeStatus(ctx context.Context, in *PollQRCodeStatusReq, opts ...grpc.CallOption) (*PollQRCodeStatusResp, error)
		SendMessage(ctx context.Context, in *SendMessageReq, opts ...grpc.CallOption) (*SendMessageResp, error)
		GetUpdates(ctx context.Context, in *GetUpdatesReq, opts ...grpc.CallOption) (*GetUpdatesResp, error)
	}

	defaultIlink struct {
		cli zrpc.Client
	}
)

func NewIlink(cli zrpc.Client) Ilink {
	return &defaultIlink{
		cli: cli,
	}
}

func (m *defaultIlink) GetQRCode(ctx context.Context, in *GetQRCodeReq, opts ...grpc.CallOption) (*GetQRCodeResp, error) {
	client := ilink.NewIlinkClient(m.cli.Conn())
	return client.GetQRCode(ctx, in, opts...)
}

func (m *defaultIlink) PollQRCodeStatus(ctx context.Context, in *PollQRCodeStatusReq, opts ...grpc.CallOption) (*PollQRCodeStatusResp, error) {
	client := ilink.NewIlinkClient(m.cli.Conn())
	return client.PollQRCodeStatus(ctx, in, opts...)
}

func (m *defaultIlink) SendMessage(ctx context.Context, in *SendMessageReq, opts ...grpc.CallOption) (*SendMessageResp, error) {
	client := ilink.NewIlinkClient(m.cli.Conn())
	return client.SendMessage(ctx, in, opts...)
}

func (m *defaultIlink) GetUpdates(ctx context.Context, in *GetUpdatesReq, opts ...grpc.CallOption) (*GetUpdatesResp, error) {
	client := ilink.NewIlinkClient(m.cli.Conn())
	return client.GetUpdates(ctx, in, opts...)
}
