// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type ApplicationData struct {
	Id        int64  `json:"id"`
	Token     string `json:"token"`
	Name      string `json:"name"`
	CreatedAt string `json:"created_at"`
}

type ApplicationInfo struct {
	Id          int64  `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	CreatedAt   string `json:"created_at"`
	LastUsedAt  string `json:"last_used_at,optional"`
}

type BaseResp struct {
	Code int32  `json:"code"`
	Msg  string `json:"msg"`
}

type ChangePasswordReq struct {
	OldPassword string `json:"old_password"`
	NewPassword string `json:"new_password"`
}

type ChangePasswordResp struct {
	Code int32  `json:"code"`
	Msg  string `json:"msg"`
}

type ClientInfo struct {
	Id          int64  `json:"id"`
	Name        string `json:"name"`
	Status      string `json:"status"`
	IlinkUserId string `json:"ilink_user_id,optional"`
	CreatedAt   string `json:"created_at"`
}

type ClientQRData struct {
	ClientId  int64  `json:"client_id"`
	QrcodeUrl string `json:"qrcode_url"`
}

type ClientStatusData struct {
	Status      string `json:"status"`
	IlinkUserId string `json:"ilink_user_id,optional"`
}

type CreateApplicationReq struct {
	Name        string `json:"name"`
	Description string `json:"description,optional"`
}

type CreateApplicationResp struct {
	Code int32           `json:"code"`
	Msg  string          `json:"msg"`
	Data ApplicationData `json:"data"`
}

type CreateClientReq struct {
	Name string `json:"name"`
}

type CreateClientResp struct {
	Code int32        `json:"code"`
	Msg  string       `json:"msg"`
	Data ClientQRData `json:"data"`
}

type CreateMessageReq struct {
	Title    string `json:"title,optional"`
	Message  string `json:"message"`
	Priority int32  `json:"priority,optional"`
}

type CreateMessageResp struct {
	Code int32       `json:"code"`
	Msg  string      `json:"msg"`
	Data MessageData `json:"data"`
}

type DeleteApplicationReq struct {
	Id string `path:"id"`
}

type DeleteApplicationResp struct {
	Code int32  `json:"code"`
	Msg  string `json:"msg"`
}

type DeleteClientReq struct {
	Id string `path:"id"`
}

type DeleteClientResp struct {
	Code int32  `json:"code"`
	Msg  string `json:"msg"`
}

type DeleteMessageReq struct {
	Id string `path:"id"`
}

type DeleteMessageResp struct {
	Code int32  `json:"code"`
	Msg  string `json:"msg"`
}

type HealthResp struct {
	ServiceName string `json:"serviceName"`
	Timestamp   int64  `json:"timestamp"`
	Message     string `json:"message"`
}

type ListApplicationsResp struct {
	Code int32             `json:"code"`
	Msg  string            `json:"msg"`
	Data []ApplicationInfo `json:"data"`
}

type ListClientsResp struct {
	Code int32        `json:"code"`
	Msg  string       `json:"msg"`
	Data []ClientInfo `json:"data"`
}

type ListMessagesReq struct {
	Limit int64 `form:"limit,default=20"`
	Since int64 `form:"since,optional"`
}

type ListMessagesResp struct {
	Code int32         `json:"code"`
	Msg  string        `json:"msg"`
	Data []MessageInfo `json:"data"`
}

type LoginData struct {
	Token string   `json:"token"`
	User  UserInfo `json:"user"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Code int32     `json:"code"`
	Msg  string    `json:"msg"`
	Data LoginData `json:"data"`
}

type MessageData struct {
	Id       int64  `json:"id"`
	Title    string `json:"title"`
	Message  string `json:"message"`
	Priority int32  `json:"priority"`
	Date     string `json:"date"`
}

type MessageInfo struct {
	Id            int64  `json:"id"`
	ApplicationId int64  `json:"application_id"`
	Title         string `json:"title"`
	Message       string `json:"message"`
	Priority      int32  `json:"priority"`
	Date          string `json:"date"`
}

type PollClientStatusReq struct {
	ClientId int64 `form:"client_id"`
}

type PollClientStatusResp struct {
	Code int32            `json:"code"`
	Msg  string           `json:"msg"`
	Data ClientStatusData `json:"data"`
}

type RegisterReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type RegisterResp struct {
	Code int32     `json:"code"`
	Msg  string    `json:"msg"`
	Data LoginData `json:"data"`
}

type UserInfo struct {
	Id        int64  `json:"id"`
	Username  string `json:"username"`
	CreatedAt string `json:"created_at"`
}
