// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type ApplicationInfo struct {
	Id          int64  `json:"id"`                    // 应用 ID
	Name        string `json:"name"`                  // 应用名称
	Description string `json:"description"`           // 应用描述
	CreatedAt   string `json:"created_at"`            // 创建时间
	LastUsedAt  string `json:"last_used_at,optional"` // 最后使用时间
}

type ChangePasswordReq struct {
	OldPassword string `json:"old_password"` // 旧密码
	NewPassword string `json:"new_password"` // 新密码
}

type ChangePasswordResp struct {
}

type ClientInfo struct {
	Id          int64  `json:"id"`                     // 客户端 ID
	Name        string `json:"name"`                   // 客户端名称
	Status      string `json:"status"`                 // 状态
	IlinkUserId string `json:"ilink_user_id,optional"` // iLink 用户 ID
	CreatedAt   string `json:"created_at"`             // 创建时间
}

type CreateApplicationReq struct {
	Name        string `json:"name"`                 // 应用名称
	Description string `json:"description,optional"` // 应用描述
}

type CreateApplicationResp struct {
	Id        int64  `json:"id"`         // 应用 ID
	Token     string `json:"token"`      // 应用 Token（用于推送鉴权）
	Name      string `json:"name"`       // 应用名称
	CreatedAt string `json:"created_at"` // 创建时间
}

type CreateClientReq struct {
	Name string `json:"name"` // 客户端名称
}

type CreateClientResp struct {
	ClientId  int64  `json:"client_id"`  // 客户端 ID
	QrcodeUrl string `json:"qrcode_url"` // 二维码链接
}

type CreateMessageReq struct {
	AppToken string `json:"app_token"`         // 应用 Token（用于推送鉴权）
	Title    string `json:"title,optional"`    // 消息标题
	Message  string `json:"message"`           // 消息内容
	Priority int32  `json:"priority,optional"` // 优先级
}

type CreateMessageResp struct {
	Id       int64  `json:"id"`       // 消息 ID
	Title    string `json:"title"`    // 消息标题
	Message  string `json:"message"`  // 消息内容
	Priority int32  `json:"priority"` // 优先级
	Date     string `json:"date"`     // 消息日期
}

type DeleteApplicationReq struct {
	Id int64 `path:"id"` // 应用 ID
}

type DeleteApplicationResp struct {
}

type DeleteClientReq struct {
	Id int64 `path:"id"` // 客户端 ID
}

type DeleteClientResp struct {
}

type DeleteMessageReq struct {
	Id int64 `path:"id"` // 消息 ID
}

type DeleteMessageResp struct {
}

type HealthResp struct {
	ServiceName string `json:"service_name"` // 服务名称
	Timestamp   int64  `json:"timestamp"`    // 服务器当前时间戳
	Message     string `json:"message"`      // 响应消息，e.g. "ok"
}

type ListApplicationsReq struct {
	Page     int `form:"page,default=1"`       // 页码，默认 1
	PageSize int `form:"page_size,default=20"` // 每页条数，默认 20
}

type ListApplicationsResp struct {
	PageInfo PageInfo          `json:"page_info"` // 分页信息
	List     []ApplicationInfo `json:"list"`      // 应用列表
}

type ListClientsReq struct {
	Page     int `form:"page,default=1"`       // 页码，默认 1
	PageSize int `form:"page_size,default=20"` // 每页条数，默认 20
}

type ListClientsResp struct {
	PageInfo PageInfo     `json:"page_info"` // 分页信息
	List     []ClientInfo `json:"list"`      // 客户端列表
}

type ListMessagesReq struct {
	Limit int64 `form:"limit,default=20"` // 每页数量，默认 20
	Since int64 `form:"since,optional"`   // 游标，返回此 ID 之前的消息
}

type ListMessagesResp struct {
	List []MessageInfo `json:"list"` // 消息列表
}

type LoginReq struct {
	Username string `json:"username"` // 用户名
	Password string `json:"password"` // 密码
}

type LoginResp struct {
	Token        string   `json:"token"`         // Access Token (15分钟过期)
	RefreshToken string   `json:"refresh_token"` // Refresh Token (7天过期)
	User         UserInfo `json:"user"`          // 用户信息
}

type MessageInfo struct {
	Id            int64  `json:"id"`             // 消息 ID
	ApplicationId int64  `json:"application_id"` // 所属应用 ID
	Title         string `json:"title"`          // 消息标题
	Message       string `json:"message"`        // 消息内容
	Priority      int32  `json:"priority"`       // 优先级
	Date          string `json:"date"`           // 消息日期
}

type PageInfo struct {
	Page       int   `json:"page"`        // 当前页码（从1开始）
	PageSize   int   `json:"page_size"`   // 每页条数
	Total      int64 `json:"total"`       // 总记录数
	TotalPages int   `json:"total_pages"` // 总页数
}

type PollClientStatusReq struct {
	ClientId int64 `form:"client_id"` // 客户端 ID
}

type PollClientStatusResp struct {
	Status      string `json:"status"`                 // 状态：pending/connected/disconnected
	IlinkUserId string `json:"ilink_user_id,optional"` // iLink 用户 ID（连接后返回）
}

type ProfileResp struct {
	User UserInfo `json:"user"` // 用户信息
}

type RefreshReq struct {
	RefreshToken string `json:"refresh_token"` // Refresh Token
}

type RefreshResp struct {
	Token        string `json:"token"`         // 新的 Access Token
	RefreshToken string `json:"refresh_token"` // 新的 Refresh Token (轮换)
}

type RegisterReq struct {
	Username string `json:"username"` // 用户名
	Password string `json:"password"` // 密码
}

type RegisterResp struct {
	Token        string   `json:"token"`         // Access Token (15分钟过期)
	RefreshToken string   `json:"refresh_token"` // Refresh Token (7天过期)
	User         UserInfo `json:"user"`          // 用户信息
}

type UserInfo struct {
	Id        int64  `json:"id"`         // 用户 ID
	Username  string `json:"username"`   // 用户名
	CreatedAt string `json:"created_at"` // 创建时间
}
